config/routes.rb
Rails.application.routes.draw do
  resources :clients
  resources :schedules
  resources :services
  resources :users

  scope :auth do
    # resource :sign_in, only: [:new, :create, :destroy], controller: :sessions
    scope :users, controller: :sessions do
      get :sign_in, action: :new
      post :sign_in, action: :create
      patch :sign_in, action: :create
      delete :sign_in, action: :destroy
    end

    scope :users, controller: :registrations do
      get :sign_up, action: :new
      post :sign_up, action: :create
      patch :sign_up, action: :create

      get :profile, action: :edit
      patch :profile, action: :update
    end
    # resource :sign_up, only: [:new, :create], controller: :registrations
  end

  root to: "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/service.rb
class Service < ApplicationRecord
  has_many :schedules

  validates :name, :kind, presence: true

  extend Enumerize
  enumerize :kind, in: [:massage, :treatment]
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  # GET /services
  # GET /services.json
  def index
    @services = Service.all
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: "Service was successfully created." }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: "Service was successfully updated." }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: "Service was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_service
    @service = Service.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def service_params
    params.require(:service).permit(:name, :kind)
  end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.slim
= simple_form_for @service, html: { class: "form form-horizontal grade" } do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :kind, as: :select, collection: Service.kind.options

  .btn-group 
    = f.button :submit, class: "btn btn-primary"
    = link_to t('.cancel'), services_path, :class => 'btn btn-secondary'

app/views/services/edit.html.slim
- model_class = Service
.page-header
  h1= t('.edit', :model => model_class.model_name.human.titleize)
= render :partial => "form"

app/views/services/index.html.slim
- model_class = Service
.page-header
  h1= t '.title', :default => model_class.model_name.human.pluralize.titleize

table.table.table-striped
  thead
    tr
      th= model_class.human_attribute_name(:id)
      th= model_class.human_attribute_name(:name)
      th= model_class.human_attribute_name(:kind)
      th= t('.actions')
  tbody
    - @services.each do |service|
      tr
        td= link_to service.id, service_path(service)
        td= service.name
        td= service.kind.text
        td
          - if can? :read, Service
            = link_to t('.show'), service_path(service), :class => 'badge badge-light mr-1'
          - if can? :manage, Service
            = link_to t('.edit'), edit_service_path(service), :class => 'badge badge-light mr-1'
            = link_to t('.destroy'), service_path(service), :method => :delete, :data => { :confirm => t('.confirm') }, :class => 'badge badge-danger mr-1'
- if can? :manage, Service
  = link_to t('.new'), new_service_path, :class => 'btn btn-primary'

app/views/services/new.html.slim
- model_class = Service
.page-header
  h1 = t('.title', :model => model_class.model_name.human.titleize)
= render :partial => "form"

app/views/services/show.html.slim
- model_class = Service
.page-header
  h1=t '.title', :default => model_class.model_name.human.titleize

.row
  .col
    strong= model_class.human_attribute_name(:name) + ': '
    = @service.name
  .col
    strong= model_class.human_attribute_name(:kind) + ': '
    = @service.kind
.row.mt-4
  .col
    .btn-group
      - if can? :read, Service
        = link_to t('.back'), services_path, :class => 'btn btn-secondary'
      - if can? :manage, Service
        = link_to t('.edit'), edit_service_path(@service), :class => 'btn btn-secondary'
        = link_to t('.destroy'), service_path(@service), :method => "delete", :data => { :confirm => t('.confirm') }, :class => 'btn btn-danger'