config/routes.rb
Rails.application.routes.draw do
  resources :clients
  resources :schedules
  resources :services
  resources :users

  scope :auth do
    # resource :sign_in, only: [:new, :create, :destroy], controller: :sessions
    scope :users, controller: :sessions do
      get :sign_in, action: :new
      post :sign_in, action: :create
      patch :sign_in, action: :create
      delete :sign_in, action: :destroy
    end

    scope :users, controller: :registrations do
      get :sign_up, action: :new
      post :sign_up, action: :create
      patch :sign_up, action: :create

      get :profile, action: :edit
      patch :profile, action: :update
    end
    # resource :sign_up, only: [:new, :create], controller: :registrations
  end

  root to: "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  attribute :session_duration, :duration

  belongs_to :service
  belongs_to :client

  validates :start_time, :session_duration, presence: true
  validate :validate_start_time_minimum_time,
    :validate_start_time_cannot_be_in_the_past,
    :validate_end_time_maximum_time, if: :start_time

  def end_time
    if start_time and session_duration.present?
      start_time + session_duration
    else
      start_time
    end
  rescue
    nil
  end

  def validate_start_time_minimum_time
    min_hour = 8

    errors.add :start_time, I18n.t("errors.schedule.wrong_range.minimum", :min_hour => min_hour) if start_time.hour < min_hour
  end

  def validate_end_time_maximum_time
    max_hour = 16
    errors.add :session_duration, I18n.t("errors.schedule.wrong_range.maximum", :max_hour => max_hour) if end_time.hour >= max_hour and end_time.min != 0
  end

  def validate_start_time_cannot_be_in_the_past
    if start_time.present? && start_time < Date.today
      errors.add(:start_time, I18n.t("errors.schedule.not_in_past"))
    end
  end

  def cancel_duration
    service.kind.massage? ? 1.day : 2.days
  end

  def cancelable?
    start_time.present? && start_time >= DateTime.now + cancel_duration
  end

  def editable?
    self.cancelable?
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  load_and_authorize_resource
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]

  # GET /schedules
  # GET /schedules.json
  def index
    @schedules = Schedule.all
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
  end

  # GET /schedules/new
  def new
    @schedule = Schedule.new
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /schedules
  # POST /schedules.json
  def create
    result = CreateSchedule.call(params: schedule_params, client: current_user.client)
    @schedule = result.schedule

    if result.success?
      redirect_to @schedule, notice: "Schedule was successfully created."
    else
      flash.now[:error] = result.message if result.message.present?
      # flash.now[:error] = result.error if result.error.present?
      render :new
    end
  end

  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to @schedule, notice: "Schedule was successfully updated." }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    result = CancelSchedule.call(schedule: @schedule)

    if result.success?
      redirect_to schedules_url, notice: "Schedule was successfully destroyed."
    else
      redirect_to schedules_url, :flash => {:error => result.message}
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_schedule
    @schedule = Schedule.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def schedule_params
    params.require(:schedule).permit(:start_time, :session_duration, :service_id, :client_id)
  end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_form.html.slim
= simple_form_for @schedule, html: { class: "form form-horizontal grade" } do |f|
  = f.error_notification

  .row
    .col  
      = f.association :service
  .row
    .col
      = f.input :start_time
    .col
      = f.input :session_duration, as: :select, collection: [["30 minutes","PT30M"], ["1 hour","PT1H"] ], include_blank: true,  selected: @schedule.session_duration.try(:iso8601)
  .btn-group.mt-4
    = f.button :submit, class: "btn btn-primary"
    = link_to t('.cancel'), schedules_path, :class => 'btn btn-secondary'

app/views/schedules/edit.html.slim
- model_class = Schedule
.page-header
  h1= t('.edit', :model => model_class.model_name.human.titleize)
= render :partial => "form"

app/views/schedules/index.html.slim
- model_class = Schedule
.page-header
  h1= t '.title', :default => model_class.model_name.human.pluralize.titleize

table.table.table-striped
  thead
    tr
      th= model_class.human_attribute_name(:id)
      th= model_class.human_attribute_name(:client_id)
      th= model_class.human_attribute_name(:service_id)
      th= model_class.human_attribute_name(:start_time)
      th= model_class.human_attribute_name(:duration)
      th= t('.actions')
  tbody
    - @schedules.each do |schedule|
      tr
        td= link_to schedule.id, schedule_path(schedule)
        td= schedule.client.name
        td= schedule.service.name
        td= l schedule.start_time, format: :long
        td= t schedule.session_duration
        td
          - if can? :read, Schedule
            = link_to t('.show'), schedule_path(schedule), :class => 'badge badge-light mr-1'
          - if can? :update, schedule
            = link_to t('.edit'), edit_schedule_path(schedule), :class => 'badge badge-light mr-1'
          - if can? :destroy, schedule
            = link_to t('.cancel'), schedule_path(schedule), :method => :delete, :data => { :confirm => t('.confirm') }, :class => 'badge badge-danger mr-1'
- if can? :create, Schedule
  = link_to t('.new'), new_schedule_path, :class => 'btn btn-primary'

app/views/schedules/new.html.slim
- model_class = Schedule
.page-header
  h1 = t('.title')
= render :partial => "form"

app/views/schedules/show.html.slim
- model_class = Schedule
.page-header
  h1=t '.title', :default => model_class.model_name.human.titleize

h2= @schedule.service.name
.row
  .col
    strong= model_class.human_attribute_name(:start_time) + ': '
    = l @schedule.start_time, format: :long
  .col
    strong= model_class.human_attribute_name(:duration) + ': '
    = @schedule.session_duration.pretty_inspect
    
.row.mt-4
  .col
    .btn-group.mr-3
      - if can? :read, Schedule
        = link_to t('.home'), root_path, :class => 'btn btn-secondary'
    .btn-group  
      - if can? :update, @schedule
        = link_to t('.edit'), edit_schedule_path(@schedule), :class => 'btn btn-secondary'
      - if can? :destroy, @schedule
        = link_to t('.cancel'), schedule_path(@schedule), :method => "delete", :data => { :confirm => t('.confirm') }, :class => 'btn btn-danger'