config/routes.rb
Rails.application.routes.draw do
  resources :clients
  resources :schedules
  resources :services
  resources :users

  scope :auth do
    # resource :sign_in, only: [:new, :create, :destroy], controller: :sessions
    scope :users, controller: :sessions do
      get :sign_in, action: :new
      post :sign_in, action: :create
      patch :sign_in, action: :create
      delete :sign_in, action: :destroy
    end

    scope :users, controller: :registrations do
      get :sign_up, action: :new
      post :sign_up, action: :create
      patch :sign_up, action: :create

      get :profile, action: :edit
      patch :profile, action: :update
    end
    # resource :sign_up, only: [:new, :create], controller: :registrations
  end

  root to: "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/client.rb
class Client < ApplicationRecord
  has_one :user

  validates :name, :document, :cellphone, presence: true
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  load_and_authorize_resource
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: "Client was successfully created." }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: "Client was successfully updated." }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: "Client was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_client
    @client = Client.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def client_params
    params.require(:client).permit(:name, :surname, :document, :cellphone, :email, :password, :password_confirmation, :address)
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.slim
= simple_form_for @client, html: { class: "form form-horizontal grade" } do |f|
  = f.error_notification

  .row
    .col= f.input :name
    .col= f.input :surname
  
  .row  
    .col= f.input :document
    .col= f.input :cellphone

  .row  
    .col= f.input :address

  .btn-group 
    = f.button :submit, class: "btn btn-primary"
    = link_to t('.cancel'), clients_path, :class => 'btn btn-secondary'

app/views/clients/edit.html.slim
- model_class = Client
.page-header
  h1= t('.edit', :model => model_class.model_name.human.titleize)
= render :partial => "form"

app/views/clients/index.html.slim
- model_class = Client
.page-header
  h1= t '.title', :default => model_class.model_name.human.pluralize.titleize

table.table.table-striped
  thead
    tr
      th= model_class.human_attribute_name(:id)
      th= model_class.human_attribute_name(:name)
      th= model_class.human_attribute_name(:surname)
      th= t('.actions')
  tbody
    - @clients.each do |client|
      tr
        td= link_to client.id, client_path(client)
        td= client.name
        td= client.surname
        td
          - if can? :read, Client
            = link_to t('.show'), client_path(client), :class => 'badge badge-light mr-1'
          - if can? :manage, Client
            = link_to t('.edit'), edit_client_path(client), :class => 'badge badge-light mr-1'
            = link_to t('.destroy'), client_path(client), :method => :delete, :data => { :confirm => t('.confirm') }, :class => 'badge badge-danger mr-1'
- if can? :manage, Client
  = link_to t('.new'), new_client_path, :class => 'btn btn-primary'

app/views/clients/new.html.slim
- model_class = Client
.page-header
  h1 = t('.title', :model => model_class.model_name.human.titleize)
= render :partial => "form"

app/views/clients/show.html.slim
- model_class = Client
.page-header
  h1=t '.title', :default => model_class.model_name.human.titleize

.row
  .col
    strong= model_class.human_attribute_name(:name) + ': '
    = @client.name
  .col
    strong= model_class.human_attribute_name(:surname) + ': '
    = @client.surname
.row
  .col
    strong= model_class.human_attribute_name(:document) + ': '
    = @client.document
  .col
    strong= model_class.human_attribute_name(:cellphone) + ': '
    = @client.cellphone
.row.mt-4
  .col
    .btn-group
      - if can? :read, Client
        = link_to t('.back'), clients_path, :class => 'btn btn-secondary'
      - if can? :manage, Client
        = link_to t('.edit'), edit_client_path(@client), :class => 'btn btn-secondary'
        = link_to t('.destroy'), client_path(@client), :method => "delete", :data => { :confirm => t('.confirm') }, :class => 'btn btn-danger'