config/routes.rb
Rails.application.routes.draw do
  resources :clients
  resources :schedules
  resources :services
  resources :users

  scope :auth do
    # resource :sign_in, only: [:new, :create, :destroy], controller: :sessions
    scope :users, controller: :sessions do
      get :sign_in, action: :new
      post :sign_in, action: :create
      patch :sign_in, action: :create
      delete :sign_in, action: :destroy
    end

    scope :users, controller: :registrations do
      get :sign_up, action: :new
      post :sign_up, action: :create
      patch :sign_up, action: :create

      get :profile, action: :edit
      patch :profile, action: :update
    end
    # resource :sign_up, only: [:new, :create], controller: :registrations
  end

  root to: "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8"
    
    title= content_for?(:title) ? yield(:title) : ClinicalAgenda
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' 
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    
  body
    nav.navbar.navbar-expand-lg.navbar-light.bg-light
      a.navbar-brand href="#" ClinicalAgenda
      button.navbar-toggler type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
        span.navbar-toggler-icon

      .collapse.navbar-collapse.navbar-responsive-collapse id="navbarSupportedContent"
        ul.nav.navbar-nav
          li.nav-item
              = link_to t('.home'), root_path, class: 'nav-link'
          - if can? :read, Schedule
            li.nav-item
              = link_to Schedule.model_name.human(count: 2).titleize, schedules_path, class: 'nav-link'
          - if user_signed_in?      

            li.nav-item.dropdown
              a.nav-link.dropdown-toggle data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false" 
                = t('.menus.profile')
              div.dropdown-menu
                span.nav-link style="width: 250px"
                  = "#{current_user.client.name} #{current_user.client.surname}"
                .dropdown-divider
                = link_to t('.edit.profile'), profile_path, class: 'nav-link'
                .dropdown-divider
                = link_to t('.logout'), sign_in_path, method: :delete, class: 'nav-link'
                
                
          - else
            li.nav-item= link_to t('.login'), sign_in_path, class: 'nav-link'

    .container
      .row
        .col
          
          = render partial: "shared/flash_messages", flash: flash
          = yield
      footer.mt-5
        span &copy; Clinical Agenda 2018